---
mesos_version: "1.5.0"
mesos_checksum: "sha256:a9acc24659d414abde1e2680877e6fb18e00654a43ef9ce6b03d68912a1a6aee"
mesos_package_url: "https://github.com/ueisele/dist-packaging-mesos/releases/download/0.2.0/mesos_{{ mesos_version }}-0.2.0.debian9_amd64.deb"
#mesos_checksum: "sha256:c7e265f920998142d716c0afd442eb7276f66b24225afbf0248e33e39c79b956"
#mesos_package_url: "http://repos.mesosphere.com/debian/pool/main/m/mesos/mesos_{{ mesos_version }}-2.0.1.debian9_amd64.deb"

zookeeper_hosts:
  - localhost

mesos_master_hosts:
  - localhost

mesos_zk: "zk://{% for host in zookeeper_hosts %}{% if loop.index > 1 %},{% endif %}{{host}}:2181{% endfor %}/mesos"
mesos_master_quorum: "{{ ((mesos_master_hosts | length) / 2) | round | int }}"
mesos_master_work_dir: "/var/lib/mesos/master"
mesos_master_log_dir: "/var/log/mesos/master"
mesos_master_port: 5050
mesos_agent_work_dir: "/var/lib/mesos/agent"
mesos_agent_log_dir: "/var/log/mesos/agent"
mesos_agent_port: 5051

mesos_open_file_limit: "8192"

mesos_master_options_default:
  zk: "{{ mesos_zk }}"
  quorum: "{{ mesos_master_quorum }}"
  work_dir: "{{ mesos_master_work_dir }}"
  log_dir: "{{ mesos_master_log_dir }}"
  port: "{{ mesos_master_port }}"

mesos_agent_options_default:
  master: "{{ mesos_zk }}"
  work_dir: "{{ mesos_agent_work_dir }}"
  log_dir: "{{ mesos_agent_log_dir }}"
  port: "{{ mesos_agent_port }}"

mesos_master_options_additional: {}
mesos_agent_options_additional: {}

mesos_master_options: "{{ mesos_master_options_default | combine(mesos_master_options_additional) }}"
mesos_agent_options: "{{ mesos_agent_options_default | combine(mesos_agent_options_additional) }}"
