= Vagrant-Platform

This repository provides a Vagrant configuration that sets up a Apache Mesos cluster in HA mode with Apache ZooKeeper.
The cluster consists of three Mesos masters and three Mesos agents.

[NOTE]
====
Apache Mesos is a plain resource scheduler. Mesos itself does not support the execution of specific workload, like a shell command or a Docker container.
This is only possible with specific Mesos frameworks, for example 'Marathon' which supports the execution of shell commands or Docker containers.
====

== Prerequisites

. Install Git, Vagrant, and VirtualBox

. Install the vagrant-hostmanager plugin

    vagrant plugin install vagrant-hostmanager

. Clone repository

    git clone https://github.com/ueisele/iac-vagrant-mesos.git
    cd iac-vagrant-mesos

== Quick Start

. Start and Provision the Cluster

    ./up.sh

. Access the Apache Mesos UI

    http://discovery1:5050/

. Finally, destroy the Cluster

    ./destroy.sh

== Run Ansible Playbooks and Ad Hoc Commands

The provided inventory at './.vagrant/provisioners/ansible/inventory' can be used to run Ansible playbooks and ad hoc commands at the guest nodes.
The inventory is auto generated by Vagrant if the command `vagrant up` or `vagrant provision` is called.

[source,bash]
----
ansible all -i .vagrant/provisioners/ansible/inventory -m command -a 'ls -alh'
----

== Mesos Vagrant Documentation

* link:doc/build-mesos.adoc[Build and Install Apache Mesos form Source]
* link:doc/ansible-adhoc-mesos.adoc[Install Apache Mesos with Ansible Ad Hoc Commands]
* link:doc/execute-task-mesos.adoc[Work with Apache Mesos]
* link:doc/troubleshooting-mesos.adoc[Throubleshooting]

== Prospect

* Extract Ansible roles for Mesos in separate repository.
** Test driven infrastructure as code development.
* Add Ansible roles for several Mesos frameworks.
** Use this as environment to test and examine Mesos frameworks.
** Show Mesos frameworks for different kind of workloads, like Marathon for Docker and Spark for cluster computing.
* Develop a custom Mesos framework.
** Introduction to Mesos framework development and a closer look on Mesos internals.
* Mesos agent on windows.
** Run Windows and Linux Docker container in a single Mesos cluser.
* Use lightweight Vagrant box to improve startup performance.
