---
- name: Create temporary install directory
  tempfile:
    state: directory
    suffix: mesos-install
  register: tempdir  

- name: Download Mesos and Check
  get_url:
    url: "{{ mesos_package_url }}"
    dest: "{{ tempdir.path }}"
    checksum: "{{ mesos_checksum }}"
    timeout: 100
  register: package  
  until: package|succeeded
  retries: 5 

- name: Install Mesos
  apt:
    deb: "{{ package.dest }}"

- name: Ensure default Mesos options are absent
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/default/mesos
    - /etc/default/mesos-master
    - /etc/default/mesos-slave
    - /etc/mesos/zk

- name: Ensure default Mesos options are touched
  file:
    path: "{{ item }}"
    state: touch
  with_items:
    - /etc/default/mesos
    - /etc/default/mesos-master
    - /etc/default/mesos-slave

- name: Ensure open file limit is set
  copy:
    content: "ULIMIT=\"-n {{ mesos_open_file_limit }}\""
    dest: /etc/default/mesos

- name: Ensure Mesos master options are set
  copy:
    content: "{{ item.value }}"
    dest: /etc/mesos-master/{{ item.key }}
  with_dict: "{{ mesos_master_options }}"

- name: Ensure Mesos agent options are set
  copy:
    content: "{{ item.value }}"
    dest: /etc/mesos-slave/{{ item.key }}
  with_dict: "{{ mesos_agent_options }}"

- name: "Ensure service Mesos master is {{ mesos_master_systemd_state }}"
  systemd:
    name: mesos-master
    enabled: "{{ mesos_master_systemd_enabled }}"
    state: "{{ mesos_master_systemd_state }}"

- name: "Ensure service Mesos agent is {{ mesos_agent_systemd_state }}"
  systemd:
    name: mesos-slave
    enabled: "{{ mesos_agent_systemd_enabled }}"
    state: "{{ mesos_agent_systemd_state }}"

- name: Ensure Mesos Master Http is registerd as Consul service
  template: src=mesosmasterhttp.consulservice.json.j2 dest=/etc/consul.d/mesosmasterhttp.consulservice.json
  notify: restart consul agent
  when: is_mesos_master == true

- name: Ensure Mesos Agent Http is registerd as Consul service
  template: src=mesosagenthttp.consulservice.json.j2 dest=/etc/consul.d/mesosagenthttp.consulservice.json
  notify: restart consul agent
  when: is_mesos_master != true  