---
- name: Fix libssl version missmatch in Debian Stretch
  apt:
    deb: "http://ftp.de.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u6_amd64.deb"
  tags: bootstrap
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'
  
- name: Apt Install Mesos
  apt:
    deb: "{{ mesos_deb_package_url }}"
  tags: bootstrap

- name: Set Zookeeper
  command: bash -c "echo zk://{% for host in zookeeper_hosts %}{% if loop.index > 1 %},{% endif %}{{host}}:2181{% endfor %}/mesos > /etc/mesos/zk"

- name: Set Mesos Agent Configs
  command: bash -c "echo {{ item.value }} > /etc/mesos-slave/{{ item.key }}"
  with_dict: "{{ config_mesos_agent }}"

- name: Service Mesos Agent Enabled and Started
  systemd:
    name: mesos-slave
    enabled: yes
    state: started