---
- name: Download Traefik and Check
  get_url:
    url: "{{ traefik_package_url }}"
    dest: /usr/local/bin/traefik{{ traefik_version }}
    checksum: "{{ traefik_checksum }}"
    timeout: 100
  register: result  
  until: result|succeeded
  retries: 5 

- name: Ensure Traefik is Executable
  file:
    path: /usr/local/bin/traefik{{ traefik_version }}
    mode: 0755

- name: Create Symlink to Traefik Binary
  file:
    src: /usr/local/bin/traefik{{ traefik_version }}
    dest: /usr/local/bin/traefik
    state: link

- name: Create Temporary Directory for Configuration
  tempfile:
    state: directory
    prefix: traefik
  register: traefik_tmp_dir  

- name: Traefik Configuration File
  template: src=traefik.toml.j2 dest={{ traefik_tmp_dir.path }}/traefik.toml

- name: Ensure Traefik configuration is stored in Consul
  command: chdir={{ traefik_tmp_dir.path }} /usr/local/bin/traefik storeconfig --consul --consul.endpoint=127.0.0.1:8500 {{ traefik_tmp_dir.path }}/traefik.toml
  register: task_result
  until: task_result.rc == 0
  retries: 5
  delay: 5
  run_once: true

- name: Systemd Script for Traefik
  template: src=traefik.service.j2 dest=/lib/systemd/system/traefik.service

- name: Traefik Enabled and Started
  systemd:
    name: traefik
    enabled: yes
    state: restarted

- name: Ensure Traefik is registerd as Consul service
  copy: src="{{ role_path }}/files/traefik.consulservice.json" dest=/etc/consul.d/traefik.consulservice.json
  notify: restart consul agent
