---
- name: Ensure package "heartbeat" is installed
  apt:
    name: heartbeat

- name: Ensure package "net-tools" is installed
  apt:
    name: net-tools

- name: Gather Facts - Host Network Interface
  command: bash -c "ifconfig | grep -B1 `hostname -i` | grep -o '^\w*'"
  register: interface_command_output
- set_fact:
    heartbeat_interface: "{{ interface_command_output.stdout }}"

- name: Ensure heartbeat is configured
  template: src=ha.cf.j2 dest=/etc/ha.d/ha.cf

- name: Ensure haresources for heartbeat are set
  template: src=haresources.j2 dest=/etc/ha.d/haresources

- name: Ensure authkeys for heartbeat are set
  template: src=authkeys.j2 dest=/etc/ha.d/authkeys mode=0600

- stat:
    path: /lib/systemd/system/heartbeat.service
  register: heartbeat_service
- name: Ensure Heartbeat Service is Disabled
  systemd:
    name: heartbeat
    enabled: no
  when: heartbeat_service.stat.exists  

- name: Ensure Heartbeat is Registered as Systemd Service
  copy: src="{{ role_path }}/files/heartbeat.service" dest=/lib/systemd/system/heartbeat.service backup=yes

- name: Ensure Heartbeat Service is Started and Enabled
  systemd:
    daemon_reload: yes
    name: heartbeat
    enabled: yes
    state: restarted
