---
- name: Resolvconf Setup
  hosts: all
  become: yes
  roles:
    - role: resolvconf
      config_resolvconf:
        - "domain {{ domainname }}"
        - "search {{ domainname }}"

#- name: Java Setup
#  hosts: all
#  become: yes
#  roles:
#    - role: geerlingguy.java
#      java_packages: 
#        - openjdk-8-jdk

#- name: Zookeeper Cluster Setup
#  hosts: zookeeper
#  become: yes
#  roles:
#    - role: AnsibleShipyard.ansible-zookeeper
#      zookeeper_version: "3.4.11"
#      zookeeper_hosts: "{{ groups['zookeeper'] }}"

- name: Consul Setup
  hosts: consul-server:consul-agent
  become: yes
  roles:
    - role: consul
      consul_version: "1.0.1"
      consul_checksum: "sha256:eac5755a1d19e4b93f6ce30caaf7b3bd8add4557b143890b1c07f5614a667a68"
      consul_server_hosts: "{{ groups['consul-server'] }}"
      consul_domain: "consul"

#- name: Mesos Master Cluster Setup
#  hosts: mesos-master
#  become: yes
#  roles:
#    - role: mesos-master
#      zookeeper_hosts: "{{ groups['zookeeper'] }}"   
#      config_mesos_master:
#        quorum: "{{ ((groups['zookeeper'] | length) / 2) | round | int }}"

#- name: Mesos Agent Cluster Setup
#  hosts: mesos-agent
#  become: yes
#  roles:
#    - role: mesos-agent
#      zookeeper_hosts: "{{ groups['zookeeper'] }}"   
#      config_mesos_agent: {}
