---
- name: Java Setup
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.java
      java_packages: 
        - openjdk-8-jdk

- name: Zookeeper Cluster Setup
  hosts: zookeeper
  become: yes
  roles:
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_version: "3.4.11"
      zookeeper_hosts: "{{ groups['zookeeper'] }}"

#- name: Mesos Master Cluster Setup
#  hosts: mesos-master
#  become: yes
#  roles:
#    - role: mesos-master
#      zookeeper_hosts: "{{ groups['zookeeper'] }}"   
#      config_mesos_master:
#        quorum: "{{ ((groups['zookeeper'] | length) / 2) | round | int }}"

#- name: Mesos Agent Cluster Setup
#  hosts: mesos-agent
#  become: yes
#  roles:
#    - role: mesos-agent
#      zookeeper_hosts: "{{ groups['zookeeper'] }}"   
#      config_mesos_agent: {}
