---
- name: Common Tools
  hosts: all
  become: yes
  roles:
    - role: tools

- name: Resolvconf Setup
  hosts: all
  become: yes
  roles:
    - role: resolvconf
      config_resolvconf:
        - "domain {{ domainname }}"
        - "search {{ domainname }} service.consul"

- name: Java Setup
  hosts: all
  become: yes
  roles:
    - role: geerlingguy.java
      java_packages: 
        - openjdk-8-jdk

- name: Ruby Setup
  hosts: all
  become: yes
  roles:
    - role: ruby       

- name: Consul Setup
  hosts: consul
  become: yes
  roles:
    - role: consul
      consul_version: "1.0.6"
      consul_checksum: "sha256:bcc504f658cef2944d1cd703eda90045e084a15752d23c038400cf98c716ea01"
      consul_server_hosts: "{{ groups['consul-server'] }}"
      consul_domain: "consul"

- name: Traefik Setup
  hosts: public-lb
  become: yes
  roles:
    - role: traefik
      traefik_version: "1.5.3"
      traefik_checksum: "sha256:746ca25e169bbde30a065cf5cce1f628a7f54179209cdd9a7ff63b4f687dc969"
      public_domain: "public.{{ domainname }}"

- name: Heartbeat Setup for Public LB
  hosts: public-lb
  become: yes
  roles:
    - role: heartbeat
      heartbeat_authkey: "heartbeat.{{ domainname }}"
      heartbeat_virtual_ip: "{{ publiclbip }}"
      heartbeat_member_hosts: "{{ groups['public-lb'] }}"

- name: Zookeeper Setup
  hosts: zookeeper
  become: yes
  roles:
    - role: AnsibleShipyard.ansible-zookeeper
      zookeeper_version: "3.4.11"
      zookeeper_hosts: "{{ groups['zookeeper'] }}"
      tick_time: 4000

- name: Mesos Setup
  hosts: mesos
  become: yes
  roles:
    - role: mesos
      mesos_version: "1.5.0"
      mesos_checksum: "sha256:7a10ee3a05666be7b415e16cc823de4f0e49dbb0ac9fa0d0ccc664e4523818d0"
      zookeeper_hosts: "{{ groups['zookeeper'] }}"  
      mesos_master_hosts: "{{ groups['mesos-master'] }}"
      mesos_master_options_additional:
        cluster: "mesos.{{ domainname }}"
      mesos_agent_options_additional:
        isolation: "cgroups/cpu,cgroups/mem,filesystem/linux"

- name: Marathon Setup
  hosts: marathon
  become: yes
  roles:
    - role: marathon
      marathon_version: "1.5.5"
      marathon_checksum: "sha256:fe5400507092909661a71365f5a36dec2fa12ee2a6f92e248b5a074a9566973c"
      zookeeper_hosts: "{{ groups['zookeeper'] }}"
      marathon_extra_options:
        framework_name: "marathon"
        