---
traefik_version: "1.4.6"
traefik_checksum: "sha256:ce46543db09c8b885e71d8a3b89251ba4b9e1bee56f238cc05651c9eb29e32b2"
traefik_package_url: "https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_linux-amd64"