---
traefik_version: "1.5.3"
traefik_checksum: "sha256:746ca25e169bbde30a065cf5cce1f628a7f54179209cdd9a7ff63b4f687dc969"
traefik_package_url: "https://github.com/containous/traefik/releases/download/v{{ traefik_version }}/traefik_linux-amd64"