---
- name: Resolve Host Ip
  command: "hostname -i"
  register: hostname_command_output

- set_fact:
    consul_bind_ip: "{{ hostname_command_output.stdout }}"

- name: Install the package "unzip"
  apt:
    name: unzip

- name: Download Consul and Check
  get_url:
    url: "{{ consul_package_url }}"
    dest: /tmp/consul_{{ consul_version }}.zip
    checksum: "{{ consul_checksum }}"
    timeout: 100
  register: result  
  until: result|succeeded
  retries: 5  

- name: Unarchive Consul
  unarchive:
    src: /tmp/consul_{{ consul_version }}.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Add Consul User
  user:
    name: consul
    createhome: no

- name: Create Consul Data Directory
  file:
    path: /var/consul
    state: directory
    owner: consul
    group: consul
    mode: 0755

- name: Create Consul Configuration Directory
  file:
    path: /etc/consul.d
    state: directory
    mode: 0755

- name: Ensure Consul Web UI Service is registerd.
  copy: src="{{ role_path }}/files/consului.consulservice.json" dest=/etc/consul.d/consului.consulservice.json
  when: consul_server == true  

- name: Consul Server Configuration File.
  template: src=config-server.json.j2 dest=/etc/consul.d/config.json
  when: consul_server == true  

- name: Consul Client Configuration File.
  template: src=config-client.json.j2 dest=/etc/consul.d/config.json
  when: consul_server != true  

- name: Systemd Script for Consul Server.
  template: src=consul-server.service.j2 dest=/lib/systemd/system/consul-server.service
  when: consul_server == true  

- name: Systemd Script for Consul Client.
  template: src=consul-client.service.j2 dest=/lib/systemd/system/consul-client.service
  when: consul_server != true  

- name: Service Consul Server Enabled and Started
  systemd:
    name: consul-server
    enabled: yes
    state: restarted
  when: consul_server == true  

- name: Service Consul Client Enabled and Started
  systemd:
    name: consul-client
    enabled: yes
    state: restarted
  when: consul_server != true

- name: Ensure package dnsmasq is installed
  apt:
    name: dnsmasq

- name: Ensure dnsmasq forwards DNS requests to Consul
  command: sh -c "echo \"server=/{{ consul_domain }}/127.0.0.1#8600\" > /etc/dnsmasq.d/consul.conf"

- name: Service dnsmasq Enabled and Started
  systemd:
    name: dnsmasq
    enabled: yes
    state: restarted
